CLIENT_ID = "3402t0v5oqplcodactc3nf53jj"
CLIENT_SECRET = "10tuk6e2vgfaurp1gdis6eb95jh8eh7t1uonuh09rjv7m3p4ifpl"

OAUTH_ENDPOINT = "https://auth.dev.pluto-service.com/oauth2/token"
BASE_URL = "https://pulseapi.dev.pluto-service.com/v1"
LOGS_FILE_PATH = "/home/vagrant/go/src/aws/pluto/pulseapi-python-service/pulseapi-python-patient"
DATA_FILE_PATH = "/home/vagrant/go/src/aws/pluto/pulseapi-python-service/pulseapi-python-patient"

STR_CRED_INCORRECT = "Your oAuth credential is incorrect"
STR_NO_PATIENTS = "No patients were found"
STR_SERVER_ERROR = "Technical issues found"
